# General
name: Dan Haywood
description: "domain driven design, apache&nbsp;isis, restful&nbsp;objects, naked&nbsp;objects, agile, tdd"
#url: http://localhost:4000

exclude: [_README, _zzz, Gemfile.lock]

markdown: kramdown
highlighter: coderay

paginate: 50
permalink: /:year/:month/:day/:title/

# Social share and comments.
disqus-id: danhaywood
twitter: dkhaywood
github: danhaywood
google: +DanHaywood
gravatarhash: 204ef8a2259ebe0716f985f96c1c350d

linkedin: dkhaywood
youtube: TheDanHaywood


# RSS feed
rss-feed-limit: 10
rss-show-full: "no"



# from https://github.com/johncarl81/transfuse-site/blob/master/_config.yml

asciidoctor:
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font
    - hardbreaks!
